# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bm_snnsmsk/Desktop/my_workspace/PROJELER/library_PYTHON/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 348)
        Form.setMaximumSize(QtCore.QSize(600, 348))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/library.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{background-color: rgb(255, 210, 198);}\n"
"QPushButton{background-color: rgb(255, 191, 0);}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_login_email = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_login_email.setFont(font)
        self.label_login_email.setObjectName("label_login_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_login_email)
        self.lineEdit_login_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_login_email.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_login_email.setFont(font)
        self.lineEdit_login_email.setObjectName("lineEdit_login_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_login_email)
        self.label_login_parola = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_login_parola.setFont(font)
        self.label_login_parola.setObjectName("label_login_parola")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_login_parola)
        self.lineEdit_login_parola = QtWidgets.QLineEdit(Form)
        self.lineEdit_login_parola.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_login_parola.setFont(font)
        self.lineEdit_login_parola.setObjectName("lineEdit_login_parola")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_login_parola)
        self.pushButton_login = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_login)
        self.gridLayout.addLayout(self.formLayout, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kütüphane Sitemi"))
        self.label.setText(_translate("Form", "Kütüphane Sitemine Giriş"))
        self.label_login_email.setText(_translate("Form", "Email Adresi"))
        self.label_login_parola.setText(_translate("Form", "Şifre"))
        self.pushButton_login.setText(_translate("Form", "Giriş"))
import login_rc
