# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bm_snnsmsk/Desktop/my_workspace/PROJELER/library_PYTHON/rent_book_kowledge.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(573, 268)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_kitap_kiralama_bilgileri = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_kitap_kiralama_bilgileri.setFont(font)
        self.label_kitap_kiralama_bilgileri.setAlignment(QtCore.Qt.AlignCenter)
        self.label_kitap_kiralama_bilgileri.setObjectName("label_kitap_kiralama_bilgileri")
        self.gridLayout.addWidget(self.label_kitap_kiralama_bilgileri, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_kitap_adi = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_kitap_adi.setFont(font)
        self.label_kitap_adi.setObjectName("label_kitap_adi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_kitap_adi)
        self.lineEdit_kitap_adi = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_kitap_adi.setFont(font)
        self.lineEdit_kitap_adi.setReadOnly(True)
        self.lineEdit_kitap_adi.setObjectName("lineEdit_kitap_adi")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_kitap_adi)
        self.label_yazar_adi = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_yazar_adi.setFont(font)
        self.label_yazar_adi.setObjectName("label_yazar_adi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_yazar_adi)
        self.label_uye_sec = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_uye_sec.setFont(font)
        self.label_uye_sec.setObjectName("label_uye_sec")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_uye_sec)
        self.lineEdit_yazar_adi = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_yazar_adi.setFont(font)
        self.lineEdit_yazar_adi.setReadOnly(True)
        self.lineEdit_yazar_adi.setObjectName("lineEdit_yazar_adi")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_yazar_adi)
        self.comboBox_uye_sec = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_uye_sec.setFont(font)
        self.comboBox_uye_sec.setObjectName("comboBox_uye_sec")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_uye_sec)
        self.pushButton_rent_book = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_rent_book.setFont(font)
        self.pushButton_rent_book.setObjectName("pushButton_rent_book")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_rent_book)
        self.label_bookID = QtWidgets.QLabel(Dialog)
        self.label_bookID.setText("")
        self.label_bookID.setObjectName("label_bookID")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_bookID)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kitap Kiralama Bilgileri"))
        self.label_kitap_kiralama_bilgileri.setText(_translate("Dialog", "Kitap Kiralama Bilgileri"))
        self.label_kitap_adi.setText(_translate("Dialog", "Kitap Adı"))
        self.label_yazar_adi.setText(_translate("Dialog", "Yazar Adı"))
        self.label_uye_sec.setText(_translate("Dialog", "Üye seç"))
        self.pushButton_rent_book.setText(_translate("Dialog", "Kitap Kirala"))
import rent_book_kowledge_rc
