# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bm_snnsmsk/Desktop/my_workspace/PROJELER/todo_PYTHON/todo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 615)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color:#1c3879 ;\n"
"}\n"
"QListWidget{\n"
"background-color:#607eaa ;\n"
"margin :10%;\n"
"font:14pt\n"
"}\n"
"QPushButton{\n"
"background-color:#607eaa ;\n"
"margin-left :10%;\n"
"margin-right :10%;\n"
"font:14pt\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_todo = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_todo.setObjectName("listWidget_todo")
        self.gridLayout.addWidget(self.listWidget_todo, 0, 0, 1, 1)
        self.pushButton_toogle_all = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_toogle_all.setObjectName("pushButton_toogle_all")
        self.gridLayout.addWidget(self.pushButton_toogle_all, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_toogle_all.setText(_translate("MainWindow", "Toggle All"))
